# demo for tolerations
# this pod will tolerate the taint of master and also gives gurantee it is schedule on master by using nodename
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: my-app
spec:
  containers:
  - name: my-app
    image: nginx
  tolerations:
  - effect: NoExecute     
    operator: Exists
  nodeName: master1
